# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ExCoin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  inhibit_all_warnings!
  pod 'RDVTabBarController', '~> 1.1.9'
  pod 'GYDataCenter'
  pod 'FMDB', '2.6.2' 
  pod 'iOS-Echarts'
  pod 'AFNetworking', '~> 3.2.1'
  # use_frameworks!

  # Pods for ExCoin

end
